package com.model;

import java.util.Date;

public class Sychu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuId
     *
     * @mbggenerated
     */
    private Integer sychuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuName
     *
     * @mbggenerated
     */
    private String sychuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuMark
     *
     * @mbggenerated
     */
    private String sychuMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuMark1
     *
     * @mbggenerated
     */
    private String sychuMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuMark2
     *
     * @mbggenerated
     */
    private String sychuMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuMark3
     *
     * @mbggenerated
     */
    private String sychuMark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuDate
     *
     * @mbggenerated
     */
    private Date sychuDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuDate1
     *
     * @mbggenerated
     */
    private Date sychuDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuZong
     *
     * @mbggenerated
     */
    private Integer sychuZong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuJine
     *
     * @mbggenerated
     */
    private Double sychuJine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuZe
     *
     * @mbggenerated
     */
    private Double sychuZe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuType
     *
     * @mbggenerated
     */
    private Integer sychuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuType1
     *
     * @mbggenerated
     */
    private Integer sychuType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.shangpinId
     *
     * @mbggenerated
     */
    private Integer shangpinId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.shangpinName
     *
     * @mbggenerated
     */
    private String shangpinName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sptypeId
     *
     * @mbggenerated
     */
    private Integer sptypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sptypeName
     *
     * @mbggenerated
     */
    private String sptypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.yonghuId
     *
     * @mbggenerated
     */
    private Integer yonghuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.yonghuName
     *
     * @mbggenerated
     */
    private String yonghuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.yhroleId
     *
     * @mbggenerated
     */
    private Integer yhroleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.yhroleName
     *
     * @mbggenerated
     */
    private String yhroleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.yhbumenId
     *
     * @mbggenerated
     */
    private Integer yhbumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.yhbumenName
     *
     * @mbggenerated
     */
    private String yhbumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.roleName
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuImg
     *
     * @mbggenerated
     */
    private String sychuImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuImgName
     *
     * @mbggenerated
     */
    private String sychuImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuErweima
     *
     * @mbggenerated
     */
    private String sychuErweima;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.sychuErweimaName
     *
     * @mbggenerated
     */
    private String sychuErweimaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.youkeId
     *
     * @mbggenerated
     */
    private Integer youkeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sychu.youkeName
     *
     * @mbggenerated
     */
    private String youkeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuId
     *
     * @return the value of t_sychu.sychuId
     *
     * @mbggenerated
     */
    public Integer getSychuId() {
        return sychuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuId
     *
     * @param sychuId the value for t_sychu.sychuId
     *
     * @mbggenerated
     */
    public void setSychuId(Integer sychuId) {
        this.sychuId = sychuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuName
     *
     * @return the value of t_sychu.sychuName
     *
     * @mbggenerated
     */
    public String getSychuName() {
        return sychuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuName
     *
     * @param sychuName the value for t_sychu.sychuName
     *
     * @mbggenerated
     */
    public void setSychuName(String sychuName) {
        this.sychuName = sychuName == null ? null : sychuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuMark
     *
     * @return the value of t_sychu.sychuMark
     *
     * @mbggenerated
     */
    public String getSychuMark() {
        return sychuMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuMark
     *
     * @param sychuMark the value for t_sychu.sychuMark
     *
     * @mbggenerated
     */
    public void setSychuMark(String sychuMark) {
        this.sychuMark = sychuMark == null ? null : sychuMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuMark1
     *
     * @return the value of t_sychu.sychuMark1
     *
     * @mbggenerated
     */
    public String getSychuMark1() {
        return sychuMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuMark1
     *
     * @param sychuMark1 the value for t_sychu.sychuMark1
     *
     * @mbggenerated
     */
    public void setSychuMark1(String sychuMark1) {
        this.sychuMark1 = sychuMark1 == null ? null : sychuMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuMark2
     *
     * @return the value of t_sychu.sychuMark2
     *
     * @mbggenerated
     */
    public String getSychuMark2() {
        return sychuMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuMark2
     *
     * @param sychuMark2 the value for t_sychu.sychuMark2
     *
     * @mbggenerated
     */
    public void setSychuMark2(String sychuMark2) {
        this.sychuMark2 = sychuMark2 == null ? null : sychuMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuMark3
     *
     * @return the value of t_sychu.sychuMark3
     *
     * @mbggenerated
     */
    public String getSychuMark3() {
        return sychuMark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuMark3
     *
     * @param sychuMark3 the value for t_sychu.sychuMark3
     *
     * @mbggenerated
     */
    public void setSychuMark3(String sychuMark3) {
        this.sychuMark3 = sychuMark3 == null ? null : sychuMark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuDate
     *
     * @return the value of t_sychu.sychuDate
     *
     * @mbggenerated
     */
    public Date getSychuDate() {
        return sychuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuDate
     *
     * @param sychuDate the value for t_sychu.sychuDate
     *
     * @mbggenerated
     */
    public void setSychuDate(Date sychuDate) {
        this.sychuDate = sychuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuDate1
     *
     * @return the value of t_sychu.sychuDate1
     *
     * @mbggenerated
     */
    public Date getSychuDate1() {
        return sychuDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuDate1
     *
     * @param sychuDate1 the value for t_sychu.sychuDate1
     *
     * @mbggenerated
     */
    public void setSychuDate1(Date sychuDate1) {
        this.sychuDate1 = sychuDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuZong
     *
     * @return the value of t_sychu.sychuZong
     *
     * @mbggenerated
     */
    public Integer getSychuZong() {
        return sychuZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuZong
     *
     * @param sychuZong the value for t_sychu.sychuZong
     *
     * @mbggenerated
     */
    public void setSychuZong(Integer sychuZong) {
        this.sychuZong = sychuZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuJine
     *
     * @return the value of t_sychu.sychuJine
     *
     * @mbggenerated
     */
    public Double getSychuJine() {
        return sychuJine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuJine
     *
     * @param sychuJine the value for t_sychu.sychuJine
     *
     * @mbggenerated
     */
    public void setSychuJine(Double sychuJine) {
        this.sychuJine = sychuJine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuZe
     *
     * @return the value of t_sychu.sychuZe
     *
     * @mbggenerated
     */
    public Double getSychuZe() {
        return sychuZe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuZe
     *
     * @param sychuZe the value for t_sychu.sychuZe
     *
     * @mbggenerated
     */
    public void setSychuZe(Double sychuZe) {
        this.sychuZe = sychuZe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuType
     *
     * @return the value of t_sychu.sychuType
     *
     * @mbggenerated
     */
    public Integer getSychuType() {
        return sychuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuType
     *
     * @param sychuType the value for t_sychu.sychuType
     *
     * @mbggenerated
     */
    public void setSychuType(Integer sychuType) {
        this.sychuType = sychuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuType1
     *
     * @return the value of t_sychu.sychuType1
     *
     * @mbggenerated
     */
    public Integer getSychuType1() {
        return sychuType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuType1
     *
     * @param sychuType1 the value for t_sychu.sychuType1
     *
     * @mbggenerated
     */
    public void setSychuType1(Integer sychuType1) {
        this.sychuType1 = sychuType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.shangpinId
     *
     * @return the value of t_sychu.shangpinId
     *
     * @mbggenerated
     */
    public Integer getShangpinId() {
        return shangpinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.shangpinId
     *
     * @param shangpinId the value for t_sychu.shangpinId
     *
     * @mbggenerated
     */
    public void setShangpinId(Integer shangpinId) {
        this.shangpinId = shangpinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.shangpinName
     *
     * @return the value of t_sychu.shangpinName
     *
     * @mbggenerated
     */
    public String getShangpinName() {
        return shangpinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.shangpinName
     *
     * @param shangpinName the value for t_sychu.shangpinName
     *
     * @mbggenerated
     */
    public void setShangpinName(String shangpinName) {
        this.shangpinName = shangpinName == null ? null : shangpinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sptypeId
     *
     * @return the value of t_sychu.sptypeId
     *
     * @mbggenerated
     */
    public Integer getSptypeId() {
        return sptypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sptypeId
     *
     * @param sptypeId the value for t_sychu.sptypeId
     *
     * @mbggenerated
     */
    public void setSptypeId(Integer sptypeId) {
        this.sptypeId = sptypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sptypeName
     *
     * @return the value of t_sychu.sptypeName
     *
     * @mbggenerated
     */
    public String getSptypeName() {
        return sptypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sptypeName
     *
     * @param sptypeName the value for t_sychu.sptypeName
     *
     * @mbggenerated
     */
    public void setSptypeName(String sptypeName) {
        this.sptypeName = sptypeName == null ? null : sptypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.yonghuId
     *
     * @return the value of t_sychu.yonghuId
     *
     * @mbggenerated
     */
    public Integer getYonghuId() {
        return yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.yonghuId
     *
     * @param yonghuId the value for t_sychu.yonghuId
     *
     * @mbggenerated
     */
    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.yonghuName
     *
     * @return the value of t_sychu.yonghuName
     *
     * @mbggenerated
     */
    public String getYonghuName() {
        return yonghuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.yonghuName
     *
     * @param yonghuName the value for t_sychu.yonghuName
     *
     * @mbggenerated
     */
    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.yhroleId
     *
     * @return the value of t_sychu.yhroleId
     *
     * @mbggenerated
     */
    public Integer getYhroleId() {
        return yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.yhroleId
     *
     * @param yhroleId the value for t_sychu.yhroleId
     *
     * @mbggenerated
     */
    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.yhroleName
     *
     * @return the value of t_sychu.yhroleName
     *
     * @mbggenerated
     */
    public String getYhroleName() {
        return yhroleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.yhroleName
     *
     * @param yhroleName the value for t_sychu.yhroleName
     *
     * @mbggenerated
     */
    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.yhbumenId
     *
     * @return the value of t_sychu.yhbumenId
     *
     * @mbggenerated
     */
    public Integer getYhbumenId() {
        return yhbumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.yhbumenId
     *
     * @param yhbumenId the value for t_sychu.yhbumenId
     *
     * @mbggenerated
     */
    public void setYhbumenId(Integer yhbumenId) {
        this.yhbumenId = yhbumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.yhbumenName
     *
     * @return the value of t_sychu.yhbumenName
     *
     * @mbggenerated
     */
    public String getYhbumenName() {
        return yhbumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.yhbumenName
     *
     * @param yhbumenName the value for t_sychu.yhbumenName
     *
     * @mbggenerated
     */
    public void setYhbumenName(String yhbumenName) {
        this.yhbumenName = yhbumenName == null ? null : yhbumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.userId
     *
     * @return the value of t_sychu.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.userId
     *
     * @param userId the value for t_sychu.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.userName
     *
     * @return the value of t_sychu.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.userName
     *
     * @param userName the value for t_sychu.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.bumenId
     *
     * @return the value of t_sychu.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.bumenId
     *
     * @param bumenId the value for t_sychu.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.bumenName
     *
     * @return the value of t_sychu.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.bumenName
     *
     * @param bumenName the value for t_sychu.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.roleId
     *
     * @return the value of t_sychu.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.roleId
     *
     * @param roleId the value for t_sychu.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.roleName
     *
     * @return the value of t_sychu.roleName
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.roleName
     *
     * @param roleName the value for t_sychu.roleName
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuImg
     *
     * @return the value of t_sychu.sychuImg
     *
     * @mbggenerated
     */
    public String getSychuImg() {
        return sychuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuImg
     *
     * @param sychuImg the value for t_sychu.sychuImg
     *
     * @mbggenerated
     */
    public void setSychuImg(String sychuImg) {
        this.sychuImg = sychuImg == null ? null : sychuImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuImgName
     *
     * @return the value of t_sychu.sychuImgName
     *
     * @mbggenerated
     */
    public String getSychuImgName() {
        return sychuImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuImgName
     *
     * @param sychuImgName the value for t_sychu.sychuImgName
     *
     * @mbggenerated
     */
    public void setSychuImgName(String sychuImgName) {
        this.sychuImgName = sychuImgName == null ? null : sychuImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuErweima
     *
     * @return the value of t_sychu.sychuErweima
     *
     * @mbggenerated
     */
    public String getSychuErweima() {
        return sychuErweima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuErweima
     *
     * @param sychuErweima the value for t_sychu.sychuErweima
     *
     * @mbggenerated
     */
    public void setSychuErweima(String sychuErweima) {
        this.sychuErweima = sychuErweima == null ? null : sychuErweima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.sychuErweimaName
     *
     * @return the value of t_sychu.sychuErweimaName
     *
     * @mbggenerated
     */
    public String getSychuErweimaName() {
        return sychuErweimaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.sychuErweimaName
     *
     * @param sychuErweimaName the value for t_sychu.sychuErweimaName
     *
     * @mbggenerated
     */
    public void setSychuErweimaName(String sychuErweimaName) {
        this.sychuErweimaName = sychuErweimaName == null ? null : sychuErweimaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.youkeId
     *
     * @return the value of t_sychu.youkeId
     *
     * @mbggenerated
     */
    public Integer getYoukeId() {
        return youkeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.youkeId
     *
     * @param youkeId the value for t_sychu.youkeId
     *
     * @mbggenerated
     */
    public void setYoukeId(Integer youkeId) {
        this.youkeId = youkeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sychu.youkeName
     *
     * @return the value of t_sychu.youkeName
     *
     * @mbggenerated
     */
    public String getYoukeName() {
        return youkeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sychu.youkeName
     *
     * @param youkeName the value for t_sychu.youkeName
     *
     * @mbggenerated
     */
    public void setYoukeName(String youkeName) {
        this.youkeName = youkeName == null ? null : youkeName.trim();
    }
}