package com.model;

import java.util.Date;

public class Youke {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeId
     *
     * @mbggenerated
     */
    private Integer youkeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeName
     *
     * @mbggenerated
     */
    private String youkeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkePassword
     *
     * @mbggenerated
     */
    private String youkePassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeXingming
     *
     * @mbggenerated
     */
    private String youkeXingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeSex
     *
     * @mbggenerated
     */
    private Integer youkeSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeAge
     *
     * @mbggenerated
     */
    private Integer youkeAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkePhone
     *
     * @mbggenerated
     */
    private String youkePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeMark1
     *
     * @mbggenerated
     */
    private String youkeMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeMark2
     *
     * @mbggenerated
     */
    private String youkeMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeMark3
     *
     * @mbggenerated
     */
    private String youkeMark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeMark4
     *
     * @mbggenerated
     */
    private String youkeMark4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeDate1
     *
     * @mbggenerated
     */
    private Date youkeDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeDate2
     *
     * @mbggenerated
     */
    private Date youkeDate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeType1
     *
     * @mbggenerated
     */
    private Integer youkeType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeType2
     *
     * @mbggenerated
     */
    private Integer youkeType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeImg
     *
     * @mbggenerated
     */
    private String youkeImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.youkeImgName
     *
     * @mbggenerated
     */
    private String youkeImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.yhroleId
     *
     * @mbggenerated
     */
    private Integer yhroleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.yhroleName
     *
     * @mbggenerated
     */
    private String yhroleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.yhbumenId
     *
     * @mbggenerated
     */
    private Integer yhbumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_youke.yhbumenName
     *
     * @mbggenerated
     */
    private String yhbumenName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeId
     *
     * @return the value of t_youke.youkeId
     *
     * @mbggenerated
     */
    public Integer getYoukeId() {
        return youkeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeId
     *
     * @param youkeId the value for t_youke.youkeId
     *
     * @mbggenerated
     */
    public void setYoukeId(Integer youkeId) {
        this.youkeId = youkeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeName
     *
     * @return the value of t_youke.youkeName
     *
     * @mbggenerated
     */
    public String getYoukeName() {
        return youkeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeName
     *
     * @param youkeName the value for t_youke.youkeName
     *
     * @mbggenerated
     */
    public void setYoukeName(String youkeName) {
        this.youkeName = youkeName == null ? null : youkeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkePassword
     *
     * @return the value of t_youke.youkePassword
     *
     * @mbggenerated
     */
    public String getYoukePassword() {
        return youkePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkePassword
     *
     * @param youkePassword the value for t_youke.youkePassword
     *
     * @mbggenerated
     */
    public void setYoukePassword(String youkePassword) {
        this.youkePassword = youkePassword == null ? null : youkePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeXingming
     *
     * @return the value of t_youke.youkeXingming
     *
     * @mbggenerated
     */
    public String getYoukeXingming() {
        return youkeXingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeXingming
     *
     * @param youkeXingming the value for t_youke.youkeXingming
     *
     * @mbggenerated
     */
    public void setYoukeXingming(String youkeXingming) {
        this.youkeXingming = youkeXingming == null ? null : youkeXingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeSex
     *
     * @return the value of t_youke.youkeSex
     *
     * @mbggenerated
     */
    public Integer getYoukeSex() {
        return youkeSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeSex
     *
     * @param youkeSex the value for t_youke.youkeSex
     *
     * @mbggenerated
     */
    public void setYoukeSex(Integer youkeSex) {
        this.youkeSex = youkeSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeAge
     *
     * @return the value of t_youke.youkeAge
     *
     * @mbggenerated
     */
    public Integer getYoukeAge() {
        return youkeAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeAge
     *
     * @param youkeAge the value for t_youke.youkeAge
     *
     * @mbggenerated
     */
    public void setYoukeAge(Integer youkeAge) {
        this.youkeAge = youkeAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkePhone
     *
     * @return the value of t_youke.youkePhone
     *
     * @mbggenerated
     */
    public String getYoukePhone() {
        return youkePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkePhone
     *
     * @param youkePhone the value for t_youke.youkePhone
     *
     * @mbggenerated
     */
    public void setYoukePhone(String youkePhone) {
        this.youkePhone = youkePhone == null ? null : youkePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeMark1
     *
     * @return the value of t_youke.youkeMark1
     *
     * @mbggenerated
     */
    public String getYoukeMark1() {
        return youkeMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeMark1
     *
     * @param youkeMark1 the value for t_youke.youkeMark1
     *
     * @mbggenerated
     */
    public void setYoukeMark1(String youkeMark1) {
        this.youkeMark1 = youkeMark1 == null ? null : youkeMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeMark2
     *
     * @return the value of t_youke.youkeMark2
     *
     * @mbggenerated
     */
    public String getYoukeMark2() {
        return youkeMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeMark2
     *
     * @param youkeMark2 the value for t_youke.youkeMark2
     *
     * @mbggenerated
     */
    public void setYoukeMark2(String youkeMark2) {
        this.youkeMark2 = youkeMark2 == null ? null : youkeMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeMark3
     *
     * @return the value of t_youke.youkeMark3
     *
     * @mbggenerated
     */
    public String getYoukeMark3() {
        return youkeMark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeMark3
     *
     * @param youkeMark3 the value for t_youke.youkeMark3
     *
     * @mbggenerated
     */
    public void setYoukeMark3(String youkeMark3) {
        this.youkeMark3 = youkeMark3 == null ? null : youkeMark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeMark4
     *
     * @return the value of t_youke.youkeMark4
     *
     * @mbggenerated
     */
    public String getYoukeMark4() {
        return youkeMark4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeMark4
     *
     * @param youkeMark4 the value for t_youke.youkeMark4
     *
     * @mbggenerated
     */
    public void setYoukeMark4(String youkeMark4) {
        this.youkeMark4 = youkeMark4 == null ? null : youkeMark4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeDate1
     *
     * @return the value of t_youke.youkeDate1
     *
     * @mbggenerated
     */
    public Date getYoukeDate1() {
        return youkeDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeDate1
     *
     * @param youkeDate1 the value for t_youke.youkeDate1
     *
     * @mbggenerated
     */
    public void setYoukeDate1(Date youkeDate1) {
        this.youkeDate1 = youkeDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeDate2
     *
     * @return the value of t_youke.youkeDate2
     *
     * @mbggenerated
     */
    public Date getYoukeDate2() {
        return youkeDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeDate2
     *
     * @param youkeDate2 the value for t_youke.youkeDate2
     *
     * @mbggenerated
     */
    public void setYoukeDate2(Date youkeDate2) {
        this.youkeDate2 = youkeDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeType1
     *
     * @return the value of t_youke.youkeType1
     *
     * @mbggenerated
     */
    public Integer getYoukeType1() {
        return youkeType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeType1
     *
     * @param youkeType1 the value for t_youke.youkeType1
     *
     * @mbggenerated
     */
    public void setYoukeType1(Integer youkeType1) {
        this.youkeType1 = youkeType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeType2
     *
     * @return the value of t_youke.youkeType2
     *
     * @mbggenerated
     */
    public Integer getYoukeType2() {
        return youkeType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeType2
     *
     * @param youkeType2 the value for t_youke.youkeType2
     *
     * @mbggenerated
     */
    public void setYoukeType2(Integer youkeType2) {
        this.youkeType2 = youkeType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeImg
     *
     * @return the value of t_youke.youkeImg
     *
     * @mbggenerated
     */
    public String getYoukeImg() {
        return youkeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeImg
     *
     * @param youkeImg the value for t_youke.youkeImg
     *
     * @mbggenerated
     */
    public void setYoukeImg(String youkeImg) {
        this.youkeImg = youkeImg == null ? null : youkeImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.youkeImgName
     *
     * @return the value of t_youke.youkeImgName
     *
     * @mbggenerated
     */
    public String getYoukeImgName() {
        return youkeImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.youkeImgName
     *
     * @param youkeImgName the value for t_youke.youkeImgName
     *
     * @mbggenerated
     */
    public void setYoukeImgName(String youkeImgName) {
        this.youkeImgName = youkeImgName == null ? null : youkeImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.yhroleId
     *
     * @return the value of t_youke.yhroleId
     *
     * @mbggenerated
     */
    public Integer getYhroleId() {
        return yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.yhroleId
     *
     * @param yhroleId the value for t_youke.yhroleId
     *
     * @mbggenerated
     */
    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.yhroleName
     *
     * @return the value of t_youke.yhroleName
     *
     * @mbggenerated
     */
    public String getYhroleName() {
        return yhroleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.yhroleName
     *
     * @param yhroleName the value for t_youke.yhroleName
     *
     * @mbggenerated
     */
    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.yhbumenId
     *
     * @return the value of t_youke.yhbumenId
     *
     * @mbggenerated
     */
    public Integer getYhbumenId() {
        return yhbumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.yhbumenId
     *
     * @param yhbumenId the value for t_youke.yhbumenId
     *
     * @mbggenerated
     */
    public void setYhbumenId(Integer yhbumenId) {
        this.yhbumenId = yhbumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_youke.yhbumenName
     *
     * @return the value of t_youke.yhbumenName
     *
     * @mbggenerated
     */
    public String getYhbumenName() {
        return yhbumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_youke.yhbumenName
     *
     * @param yhbumenName the value for t_youke.yhbumenName
     *
     * @mbggenerated
     */
    public void setYhbumenName(String yhbumenName) {
        this.yhbumenName = yhbumenName == null ? null : yhbumenName.trim();
    }
}