package com.mapper;

import com.model.Sychu;
import com.model.Sychu;
import com.model.Uxinxi;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SychuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sychu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sychuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sychu
     *
     * @mbggenerated
     */
    int insert(Sychu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sychu
     *
     * @mbggenerated
     */
    Sychu selectByPrimaryKey(Integer sychuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sychu
     *
     * @mbggenerated
     */
    List<Sychu> selectAll(@Param("sychu")Sychu record,@Param("page")int page,@Param("rows")int rows, @Param("sdate")String sdate, @Param("edate")String edate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sychu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sychu record);
}